-- Competitive Programming Snippets for C++
local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node
local c = ls.choice_node
local fmt = require("luasnip.extras.fmt").fmt

return {
  -- Basic template
  s("cp", {
    t({"#include <bits/stdc++.h>",
      "#include <chrono>",
      "#include <fstream>",
      "using namespace std;",
      "",
      "#ifndef ONLINE_JUDGE",
      "    #include \"debug.h\"",
      "#else",
      "    #define debug(...) 42",
      "    #define _printl(...) 42",
      "#endif",
      "",
      "void fastio() {",
      "    ios::sync_with_stdio(0);",
      "    cin.tie(0);",
      "    cout.tie(0);",
      "}",
      "",
      "#pragma GCC optimize(\"O3,unroll-loops,Ofast\")",
      "#pragma GCC target(\"sse,sse2,sse3,ssse3,sse4,popcnt,abm,mmx,avx\")",
      "",
      "#define LC_HACK",
      "#ifdef LC_HACK",
      "const auto __ = []() {",
      "    struct ___ { static void _() { std::ofstream(\"display_runtime.txt\") << 0 << '\\n'; } };",
      "    std::atexit(&___::_);",
      "    return 0;",
      "}();",
      "#endif",
      "",
      "#define int long long",
      "using ll = long long;",
      "using ull = unsigned long long;",
      "using ld = long double;",
      "using pii = pair<int, int>;",
      "using pll = pair<ll, ll>;",
      "using vi = vector<int>;",
      "using vll = vector<ll>;",
      "using vpi = vector<pii>;",
      "using vpll = vector<pll>;",
      "using vvi = vector<vi>;",
      "using mii = map<int, int>;",
      "using umii = unordered_map<int, int>;",
      "using si = set<int>;",
      "",
      "const int INF = 1e18;",
      "const int MOD = 1e9 + 7;",
      "const int MOD1 = 998244353;",
      "const double EPS = 1e-9;",
      "const double PI = acos(-1.0);",
      "const int dx[] = {0, 1, 0, -1};",
      "const int dy[] = {1, 0, -1, 0};",
      "",
      "#define pb push_back",
      "#define eb emplace_back",
      "#define ff first",
      "#define ss second",
      "#define endl '\\n'",
      "#define all(x) (x).begin(), (x).end()",
      "#define rall(x) (x).rbegin(), (x).rend()",
      "#define sz(x) ((int)(x).size())",
      "#define yes cout << \"YES\\n\"",
      "#define no cout << \"NO\\n\"",
      "#define re return",
      "#define rep(i, a, b) for (int i = a; i < b; ++i)",
      "#define per(i, a, b) for (int i = a; i >= b; --i)",
      "#define each(x, a) for (auto &x : a)",
      "",
      "mt19937_64 rng(chrono::steady_clock::now().time_since_epoch().count());",
      "int rand_int(int l, int r) {",
      "    uniform_int_distribution<int> dist(l, r);",
      "    return dist(rng);",
      "}",
      "",
      "template<typename T>",
      "void read(T &x) { cin >> x; }",
      "template<typename T, typename... Args>",
      "void read(T &x, Args&... args) { read(x); read(args...); }",
      "template<typename T>",
      "void read(vector<T> &v) { for (T &x : v) cin >> x; }",
      "",
      "template<typename T>",
      "void print(const T &x) { cout << x << '\\n'; }",
      "template<typename T, typename... Args>",
      "void print(const T &x, const Args&... args) { cout << x << \" \"; print(args...); }",
      "template<typename T>",
      "void printv(const vector<T> &v) { for (auto &x : v) cout << x << \" \"; cout << '\\n'; }",
      "",
      "void solve() {",
      ""}),
    i(1),
    t({"",
      "}",
      "",
      "int32_t main() {",
      "    fastio();",
      "    int t = 1;",
      "    cin >> t;",
      "    while (t--) {",
      "        #ifndef ONLINE_JUDGE",
      "        cerr << \"=======================================================\\n\";",
      "        auto start = chrono::high_resolution_clock::now();",
      "        cerr << \"Running test case #\" << t+1 << endl;",
      "        #endif",
      "",
      "        solve();",
      "",
      "        #ifndef ONLINE_JUDGE",
      "        auto end = chrono::high_resolution_clock::now();",
      "        auto duration = chrono::duration_cast<chrono::microseconds>(end - start);",
      "        cerr << fixed << setprecision(6) << \"Execution Time: \" << duration.count() / 1e6 << \" s\\n\";",
      "        #endif",
      "    }",
      "    return 0;",
      "}"})
  }),

  -- Fast I/O
  s("fastio", {
    t({"ios_base::sync_with_stdio(false);", 
      "cin.tie(NULL);"})
  }),

  -- Debug macro
  s("debug", {
    t("#define debug(x) cout << #x << \" = \" << x << endl;")
  }),

  -- Vector declaration
  s("vec", fmt("vector<{}> {} = {{{}}};", {
    i(1, "int"),
    i(2, "v"),
    i(3)
  })),

  -- 2D Vector
  s("vec2d", fmt("vector<vector<{}>> {}({}, vector<{}>({}, {}));", {
    i(1, "int"),
    i(2, "v"),
    i(3, "n"),
    i(1),
    i(4, "m"),
    i(5, "0")
  })),

  -- Binary Search
  s("bsearch", {
    t({"int binary_search(vector<int>& arr, int target) {",
      "    int left = 0, right = arr.size() - 1;",
      "    while (left <= right) {",
      "        int mid = left + (right - left) / 2;",
      "        if (arr[mid] == target) return mid;",
      "        if (arr[mid] < target) left = mid + 1;",
      "        else right = mid - 1;",
      "    }",
      "    return -1;",
      "}"})
  }),

  -- GCD function
  s("gcd", {
    t({"int gcd(int a, int b) {",
      "    if (b == 0) return a;",
      "    return gcd(b, a % b);",
      "}"})
  }),

  -- LCM function
  s("lcm", {
    t({"int lcm(int a, int b) {",
      "    return (a / gcd(a, b)) * b;",
      "}"})
  }),

  -- Prime check
  s("isprime", {
    t({"bool is_prime(int n) {",
      "    if (n <= 1) return false;",
      "    if (n <= 3) return true;",
      "    if (n % 2 == 0 || n % 3 == 0) return false;",
      "    for (int i = 5; i * i <= n; i += 6) {",
      "        if (n % i == 0 || n % (i + 2) == 0) return false;",
      "    }",
      "    return true;",
      "}"})
  }),

  -- Sieve of Eratosthenes
  s("sieve", {
    t({"vector<bool> sieve(int n) {",
      "    vector<bool> is_prime(n + 1, true);",
      "    is_prime[0] = is_prime[1] = false;",
      "    for (int i = 2; i * i <= n; i++) {",
      "        if (is_prime[i]) {",
      "            for (int j = i * i; j <= n; j += i) {",
      "                is_prime[j] = false;",
      "            }",
      "        }",
      "    }",
      "    return is_prime;",
      "}"})
  }),

  -- Power function with modulo
  s("powmod", {
    t({"long long power(long long base, long long exp, long long mod) {",
      "    long long result = 1;",
      "    while (exp > 0) {",
      "        if (exp % 2 == 1) result = (result * base) % mod;",
      "        base = (base * base) % mod;",
      "        exp /= 2;",
      "    }",
      "    return result;",
      "}"})
  }),

  -- Factorial
  s("factorial", {
    t({"long long factorial(int n) {",
      "    if (n <= 1) return 1;",
      "    return n * factorial(n - 1);",
      "}"})
  }),

  -- Combination (nCr)
  s("ncr", {
    t({"long long nCr(int n, int r) {",
      "    if (r > n || r < 0) return 0;",
      "    if (r == 0 || r == n) return 1;",
      "    long long result = 1;",
      "    for (int i = 0; i < r; i++) {",
      "        result = result * (n - i) / (i + 1);",
      "    }",
      "    return result;",
      "}"})
  }),

  -- DFS template
  s("dfs", {
    t({"void dfs(int node, vector<vector<int>>& adj, vector<bool>& visited) {",
      "    visited[node] = true;",
      "    // Process current node",
      "    ",
      "    for (int neighbor : adj[node]) {",
      "        if (!visited[neighbor]) {",
      "            dfs(neighbor, adj, visited);",
      "        }",
      "    }",
      "}"})
  }),

  -- BFS template
  s("bfs", {
    t({"void bfs(int start, vector<vector<int>>& adj, vector<bool>& visited) {",
      "    queue<int> q;",
      "    q.push(start);",
      "    visited[start] = true;",
      "    ",
      "    while (!q.empty()) {",
      "        int node = q.front();",
      "        q.pop();",
      "        // Process current node",
      "        ",
      "        for (int neighbor : adj[node]) {",
      "            if (!visited[neighbor]) {",
      "                visited[neighbor] = true;",
      "                q.push(neighbor);",
      "            }",
      "        }",
      "    }",
      "}"})
  }),

  -- Dijkstra's algorithm
  s("dijkstra", {
    t({"vector<int> dijkstra(int start, vector<vector<pair<int, int>>>& adj) {",
      "    int n = adj.size();",
      "    vector<int> dist(n, INT_MAX);",
      "    priority_queue<pair<int, int>, vector<pair<int, int>>, greater<pair<int, int>>> pq;",
      "    ",
      "    dist[start] = 0;",
      "    pq.push({0, start});",
      "    ",
      "    while (!pq.empty()) {",
      "        int d = pq.top().first;",
      "        int u = pq.top().second;",
      "        pq.pop();",
      "        ",
      "        if (d > dist[u]) continue;",
      "        ",
      "        for (auto& edge : adj[u]) {",
      "            int v = edge.first;",
      "            int w = edge.second;",
      "            if (dist[u] + w < dist[v]) {",
      "                dist[v] = dist[u] + w;",
      "                pq.push({dist[v], v});",
      "            }",
      "        }",
      "    }",
      "    return dist;",
      "}"})
  }),

  -- Union-Find (Disjoint Set Union)
  s("dsu", {
    t({"class DSU {",
      "public:",
      "    vector<int> parent, rank;",
      "    ",
      "    DSU(int n) {",
      "        parent.resize(n);",
      "        rank.resize(n, 0);",
      "        for (int i = 0; i < n; i++) parent[i] = i;",
      "    }",
      "    ",
      "    int find(int x) {",
      "        if (parent[x] != x) parent[x] = find(parent[x]);",
      "        return parent[x];",
      "    }",
      "    ",
      "    void unite(int x, int y) {",
      "        int px = find(x), py = find(y);",
      "        if (px == py) return;",
      "        if (rank[px] < rank[py]) swap(px, py);",
      "        parent[py] = px;",
      "        if (rank[px] == rank[py]) rank[px]++;",
      "    }",
      "    ",
      "    bool connected(int x, int y) {",
      "        return find(x) == find(y);",
      "    }",
      "};"})
  }),

  -- Segment Tree
  s("segtree", {
    t({"class SegmentTree {",
      "public:",
      "    vector<int> tree;",
      "    int n;",
      "    ",
      "    SegmentTree(vector<int>& arr) {",
      "        n = arr.size();",
      "        tree.resize(4 * n);",
      "        build(arr, 0, 0, n - 1);",
      "    }",
      "    ",
      "    void build(vector<int>& arr, int node, int start, int end) {",
      "        if (start == end) {",
      "            tree[node] = arr[start];",
      "        } else {",
      "            int mid = (start + end) / 2;",
      "            build(arr, 2 * node + 1, start, mid);",
      "            build(arr, 2 * node + 2, mid + 1, end);",
      "            tree[node] = tree[2 * node + 1] + tree[2 * node + 2];",
      "        }",
      "    }",
      "    ",
      "    int query(int node, int start, int end, int l, int r) {",
      "        if (r < start || end < l) return 0;",
      "        if (l <= start && end <= r) return tree[node];",
      "        int mid = (start + end) / 2;",
      "        return query(2 * node + 1, start, mid, l, r) + query(2 * node + 2, mid + 1, end, l, r);",
      "    }",
      "    ",
      "    int query(int l, int r) {",
      "        return query(0, 0, n - 1, l, r);",
      "    }",
      "};"})
  }),

  -- Fenwick Tree (Binary Indexed Tree)
  s("fenwick", {
    t({"class FenwickTree {",
      "public:",
      "    vector<int> tree;",
      "    int n;",
      "    ",
      "    FenwickTree(int size) {",
      "        n = size;",
      "        tree.resize(n + 1, 0);",
      "    }",
      "    ",
      "    void update(int idx, int val) {",
      "        for (++idx; idx <= n; idx += idx & -idx) {",
      "            tree[idx] += val;",
      "        }",
      "    }",
      "    ",
      "    int query(int idx) {",
      "        int sum = 0;",
      "        for (++idx; idx > 0; idx -= idx & -idx) {",
      "            sum += tree[idx];",
      "        }",
      "        return sum;",
      "    }",
      "    ",
      "    int range_query(int l, int r) {",
      "        return query(r) - query(l - 1);",
      "    }",
      "};"})
  }),

  -- Trie
  s("trie", {
    t({"class Trie {",
      "public:",
      "    struct TrieNode {",
      "        TrieNode* children[26];",
      "        bool isEnd;",
      "        TrieNode() {",
      "            for (int i = 0; i < 26; i++) children[i] = nullptr;",
      "            isEnd = false;",
      "        }",
      "    };",
      "    ",
      "    TrieNode* root;",
      "    ",
      "    Trie() {",
      "        root = new TrieNode();",
      "    }",
      "    ",
      "    void insert(string word) {",
      "        TrieNode* node = root;",
      "        for (char c : word) {",
      "            int idx = c - 'a';",
      "            if (!node->children[idx]) {",
      "                node->children[idx] = new TrieNode();",
      "            }",
      "            node = node->children[idx];",
      "        }",
      "        node->isEnd = true;",
      "    }",
      "    ",
      "    bool search(string word) {",
      "        TrieNode* node = root;",
      "        for (char c : word) {",
      "            int idx = c - 'a';",
      "            if (!node->children[idx]) return false;",
      "            node = node->children[idx];",
      "        }",
      "        return node->isEnd;",
      "    }",
      "};"})
  }),

  -- Common contest macros
  s("macros", {
    t({"#define ll long long",
      "#define ull unsigned long long",
      "#define vi vector<int>",
      "#define vl vector<ll>",
      "#define vvi vector<vector<int>>",
      "#define vvl vector<vector<ll>>",
      "#define pii pair<int, int>",
      "#define pll pair<ll, ll>",
      "#define vpii vector<pair<int, int>>",
      "#define vpll vector<pair<ll, ll>>",
      "#define fi first",
      "#define se second",
      "#define pb push_back",
      "#define mp make_pair",
      "#define all(x) (x).begin(), (x).end()",
      "#define sz(x) (int)(x).size()",
      "#define rep(i, a, b) for (int i = a; i < b; i++)",
      "#define repr(i, a, b) for (int i = a; i >= b; i--)",
      "#define endl '\\n'"})
  }),

  -- Sort with custom comparator
  s("sortcmp", fmt("sort(all({}), [](const {} &a, const {} &b) {{\n    return {};\n}});", {
    i(1, "v"),
    i(2, "int"),
    i(2),
    i(3, "a < b")
  })),

  -- Map iteration
  s("mapit", fmt("for (auto& [{}, {}] : {}) {{\n    {}\n}}", {
    i(1, "key"),
    i(2, "value"),
    i(3, "map"),
    i(4, "// code")
  })),

  -- Set operations
  s("setops", {
    t({"// Set operations",
      "set<int> s1, s2, result;",
      "set_union(s1.begin(), s1.end(), s2.begin(), s2.end(), inserter(result, result.begin()));",
      "set_intersection(s1.begin(), s1.end(), s2.begin(), s2.end(), inserter(result, result.begin()));",
      "set_difference(s1.begin(), s1.end(), s2.begin(), s2.end(), inserter(result, result.begin()));"})
  }),

  -- Matrix multiplication
  s("matmul", {
    t({"vector<vector<int>> multiply(vector<vector<int>>& A, vector<vector<int>>& B) {",
      "    int n = A.size(), m = B[0].size(), p = B.size();",
      "    vector<vector<int>> C(n, vector<int>(m, 0));",
      "    for (int i = 0; i < n; i++) {",
      "        for (int j = 0; j < m; j++) {",
      "            for (int k = 0; k < p; k++) {",
      "                C[i][j] += A[i][k] * B[k][j];",
      "            }",
      "        }",
      "    }",
      "    return C;",
      "}"})
  }),

  -- Next permutation usage
  s("nextperm", {
    t({"// Generate all permutations",
      "sort(all(arr));",
      "do {",
      "    // Process current permutation",
      "    ",
      "} while (next_permutation(all(arr)));"})
  }),

  -- KMP algorithm
  s("kmp", {
    t({"vector<int> computeLPS(string pattern) {",
      "    int m = pattern.length();",
      "    vector<int> lps(m, 0);",
      "    int len = 0, i = 1;",
      "    ",
      "    while (i < m) {",
      "        if (pattern[i] == pattern[len]) {",
      "            len++;",
      "            lps[i] = len;",
      "            i++;",
      "        } else {",
      "            if (len != 0) len = lps[len - 1];",
      "            else { lps[i] = 0; i++; }",
      "        }",
      "    }",
      "    return lps;",
      "}",
      "",
      "vector<int> KMP(string text, string pattern) {",
      "    vector<int> result;",
      "    vector<int> lps = computeLPS(pattern);",
      "    int i = 0, j = 0;",
      "    ",
      "    while (i < text.length()) {",
      "        if (pattern[j] == text[i]) { i++; j++; }",
      "        if (j == pattern.length()) {",
      "            result.push_back(i - j);",
      "            j = lps[j - 1];",
      "        } else if (i < text.length() && pattern[j] != text[i]) {",
      "            if (j != 0) j = lps[j - 1];",
      "            else i++;",
      "        }",
      "    }",
      "    return result;",
      "}"})
  }),
  s("modint", {
  t({
    "template <typename T>",
    "T inverse(T a, T m) {",
    "  T u = 0, v = 1;",
    "  while (a != 0) {",
    "    T t = m / a;",
    "    m -= t * a; swap(a, m);",
    "    u -= t * v; swap(u, v);",
    "  }",
    "  assert(m == 1);",
    "  return u;",
    "}",
    "",
    "template <typename T>",
    "class Modular {",
    " public:",
    "  using Type = typename decay<decltype(T::value)>::type;",
    "",
    "  constexpr Modular() : value() {}",
    "  template <typename U>",
    "  Modular(const U& x) { value = normalize(x); }",
    "",
    "  template <typename U>",
    "  static Type normalize(const U& x) {",
    "    Type v;",
    "    if (-mod() <= x && x < mod()) v = static_cast<Type>(x);",
    "    else v = static_cast<Type>(x % mod());",
    "    if (v < 0) v += mod();",
    "    return v;",
    "  }",
    "",
    "  const Type& operator()() const { return value; }",
    "  template <typename U> explicit operator U() const { return static_cast<U>(value); }",
    "  constexpr static Type mod() { return T::value; }",
    "",
    "  Modular& operator+=(const Modular& other) { value += other.value; if (value >= mod()) value -= mod(); return *this; }",
    "  Modular& operator-=(const Modular& other) { value -= other.value; if (value < 0) value += mod(); return *this; }",
    "  Modular& operator++() { return *this += 1; }",
    "  Modular& operator--() { return *this -= 1; }",
    "  Modular operator++(int) { Modular result(*this); *this += 1; return result; }",
    "  Modular operator--(int) { Modular result(*this); *this -= 1; return result; }",
    "  Modular operator-() const { return Modular(-value); }",
    "",
    "  template <typename U = T>",
    "  typename enable_if<is_same<typename Modular<U>::Type, int>::value, Modular>::type&",
    "  operator*=(const Modular& rhs) {",
    "    value = normalize(static_cast<int64_t>(value) * static_cast<int64_t>(rhs.value));",
    "    return *this;",
    "  }",
    "",
    "  template <typename U = T>",
    "  typename enable_if<is_same<typename Modular<U>::Type, int64_t>::value, Modular>::type&",
    "  operator*=(const Modular& rhs) {",
    "    int64_t q = int64_t(static_cast<long double>(value) * rhs.value / mod());",
    "    value = normalize(value * rhs.value - q * mod());",
    "    return *this;",
    "  }",
    "",
    "  template <typename U = T>",
    "  typename enable_if<!is_integral<typename Modular<U>::Type>::value, Modular>::type&",
    "  operator*=(const Modular& rhs) {",
    "    value = normalize(value * rhs.value);",
    "    return *this;",
    "  }",
    "",
    "  Modular& operator/=(const Modular& other) { return *this *= Modular(inverse(other.value, mod())); }",
    "",
    "  friend bool operator==(const Modular& lhs, const Modular& rhs) { return lhs.value == rhs.value; }",
    "  friend bool operator!=(const Modular& lhs, const Modular& rhs) { return !(lhs == rhs); }",
    "  friend bool operator<(const Modular& lhs, const Modular& rhs) { return lhs.value < rhs.value; }",
    "",
    "  template <typename V, typename U>",
    "  friend V& operator>>(V& stream, Modular<U>& number) {",
    "    typename common_type<typename Modular<U>::Type, int64_t>::type x;",
    "    stream >> x;",
    "    number.value = Modular<U>::normalize(x);",
    "    return stream;",
    "  }",
    "",
    "  template <typename V, typename U>",
    "  friend V& operator<<(V& stream, const Modular<U>& number) { return stream << number(); }",
    "",
    " private:",
    "  Type value;",
    "};",
    "",
    "template <typename T> Modular<T> operator+(Modular<T> lhs, const Modular<T>& rhs) { return lhs += rhs; }",
    "template <typename T> Modular<T> operator-(Modular<T> lhs, const Modular<T>& rhs) { return lhs -= rhs; }",
    "template <typename T> Modular<T> operator*(Modular<T> lhs, const Modular<T>& rhs) { return lhs *= rhs; }",
    "template <typename T> Modular<T> operator/(Modular<T> lhs, const Modular<T>& rhs) { return lhs /= rhs; }",
    "",
    "template<typename T, typename U>",
    "Modular<T> power(Modular<T> a, U b) {",
    "  assert(b >= 0);",
    "  Modular<T> res = 1;",
    "  while (b > 0) {",
    "    if (b & 1) res *= a;",
    "    a *= a;",
    "    b >>= 1;",
    "  }",
    "  return res;",
    "}",
    "",
    "template <typename T>",
    "bool IsZero(const Modular<T>& number) { return number() == 0; }",
    "",
    "template <typename T>",
    "string to_string(const Modular<T>& number) { return to_string(number()); }",
    "",
    "constexpr int MOD12 = 998244353;",
    "using Mint = Modular<std::integral_constant<decay<decltype(md)>::type, MOD12>>;"
  })
}),
--sparse table for or query(formation-->nlogn) (query answer-->O(1));
s("sparseor", {
  t({
    "class SparseTable {",
    "vector<vector<int>> st;",
    "vector<int> log2;",
    "public:",
    "SparseTable(const vector<int>& a) {",
    "int n = a.size();",
    "int max_log = 32 - __builtin_clz(n);",
    "log2.resize(n + 1);",
    "log2[1] = 0;",
    "for (int i = 2; i <= n; ++i)",
    "log2[i] = log2[i / 2] + 1;",
    "st.assign(n, vector<int>(max_log));",
    "for (int i = 0; i < n; ++i)",
    "st[i][0] = a[i];",
    "for (int j = 1; (1 << j) <= n; ++j) {",
    "for (int i = 0; i + (1 << j) <= n; ++i) {",
    "st[i][j] = st[i][j - 1] | st[i + (1 << (j - 1))][j - 1];",
    "}",
    "}",
    "}",
    "int query(int l, int r) {",
    "int len = r - l + 1;",
    "int k = log2[len];",
    "return st[l][k] | st[r - (1 << k) + 1][k];",
    "}",
    "};"
  })
}),
}
