-- Auto-generated colorscheme from gvim_highlight.txt
--vim.g.colors_name = "custom_colorscheme"




vim.api.nvim_set_hl(0, "Normal", { fg = "#c0c0c0", bg = "#000000" })
vim.api.nvim_set_hl(0, "SpecialKey", { fg = "#0000ff", bold = true })
vim.api.nvim_set_hl(0, "EndOfBuffer", { link = "NonText" })
vim.api.nvim_set_hl(0, "NonText", { fg = "#0000ff", bold = true })
vim.api.nvim_set_hl(0, "Directory", { fg = "#0000ff", bold = true })
vim.api.nvim_set_hl(0, "ErrorMsg", { fg = "#ffffff", bg = "#ff0000" })
vim.api.nvim_set_hl(0, "IncSearch", { reverse = true })
vim.api.nvim_set_hl(0, "Search", { bg = "#ffff00", reverse = true })
vim.api.nvim_set_hl(0, "CurSearch", { link = "Search" })
vim.api.nvim_set_hl(0, "MoreMsg", { fg = "#2e8b57", bold = true })
vim.api.nvim_set_hl(0, "ModeMsg", { bold = true })
vim.api.nvim_set_hl(0, "LineNr", { fg = "#a52a2a", underline = true })
vim.api.nvim_set_hl(0, "LineNrAbove", {})
vim.api.nvim_set_hl(0, "LineNrBelow", {})
vim.api.nvim_set_hl(0, "CursorLineNr", { fg = "#a52a2a", bold = true, underline = true })
vim.api.nvim_set_hl(0, "CursorLineSign", { link = "SignColumn" })
vim.api.nvim_set_hl(0, "CursorLineFold", { link = "FoldColumn" })
vim.api.nvim_set_hl(0, "Question", { fg = "#2e8b57", bold = true })
vim.api.nvim_set_hl(0, "StatusLine", { bold = true, reverse = true })
vim.api.nvim_set_hl(0, "StatusLineNC", { reverse = true })
vim.api.nvim_set_hl(0, "VertSplit", { reverse = true })
vim.api.nvim_set_hl(0, "Title", { fg = "#ff00ff", bold = true })
vim.api.nvim_set_hl(0, "Visual", { bg = "#d3d3d3", reverse = true })
vim.api.nvim_set_hl(0, "VisualNOS", { bold = true, underline = true })
vim.api.nvim_set_hl(0, "WarningMsg", { fg = "#ff0000" })
vim.api.nvim_set_hl(0, "WildMenu", { fg = "#000000", bg = "#ffff00" })
vim.api.nvim_set_hl(0, "Folded", { fg = "#00008b", bg = "#d3d3d3" })
vim.api.nvim_set_hl(0, "FoldColumn", { fg = "#00008b", bg = "#bebebe" })
vim.api.nvim_set_hl(0, "DiffAdd", { bg = "#add8e6", bold = true })
vim.api.nvim_set_hl(0, "DiffChange", { bg = "#ff80ff", bold = true })
vim.api.nvim_set_hl(0, "DiffDelete", { fg = "#0000ff", bg = "#e0ffff", bold = true })
vim.api.nvim_set_hl(0, "DiffText", { bg = "#ff0000", bold = true, reverse = true })
vim.api.nvim_set_hl(0, "SignColumn", { fg = "#00008b", bg = "#bebebe" })
vim.api.nvim_set_hl(0, "Conceal", { fg = "#b3b3b3" })
vim.api.nvim_set_hl(0, "SpellBad", { bg = "#0000ff", reverse = true })
vim.api.nvim_set_hl(0, "SpellCap", { bg = "#ff0000", reverse = true })
vim.api.nvim_set_hl(0, "SpellRare", { bg = "#ff00ff", reverse = true })
vim.api.nvim_set_hl(0, "SpellLocal", { bg = "#ffff00", underline = true })
vim.api.nvim_set_hl(0, "Pmenu", { fg = "#000000", bg = "#ff80ff" })
vim.api.nvim_set_hl(0, "PmenuSel", { fg = "#000000", bg = "#bebebe" })
vim.api.nvim_set_hl(0, "PmenuKind", { link = "Pmenu" })
vim.api.nvim_set_hl(0, "PmenuKindSel", { link = "PmenuSel" })
vim.api.nvim_set_hl(0, "PmenuExtra", { link = "Pmenu" })
vim.api.nvim_set_hl(0, "PmenuExtraSel", { link = "PmenuSel" })
vim.api.nvim_set_hl(0, "PmenuSbar", { bg = "#bebebe" })
vim.api.nvim_set_hl(0, "PmenuThumb", { bg = "#000000" })
vim.api.nvim_set_hl(0, "TabLine", { fg = "#000000", bg = "#d3d3d3", underline = true })
vim.api.nvim_set_hl(0, "TabLineSel", { bold = true })
vim.api.nvim_set_hl(0, "TabLineFill", { reverse = true })
vim.api.nvim_set_hl(0, "CursorColumn", { bg = "#e5e5e5", reverse = true })
vim.api.nvim_set_hl(0, "CursorLine", { bg = "#e5e5e5" })
vim.api.nvim_set_hl(0, "ColorColumn", { bg = "#ff8080", reverse = true })
vim.api.nvim_set_hl(0, "QuickFixLine", { link = "Search" })
vim.api.nvim_set_hl(0, "StatusLineTerm", { fg = "bg", bg = "DarkGreen", bold = true, reverse = true })
vim.api.nvim_set_hl(0, "StatusLineTermNC", { fg = "bg", bg = "DarkGreen", reverse = true })
vim.api.nvim_set_hl(0, "Cursor", { fg = "bg", bg = "fg" })
vim.api.nvim_set_hl(0, "lCursor", { fg = "bg", bg = "fg" })
vim.api.nvim_set_hl(0, "Normal", {})
vim.api.nvim_set_hl(0, "MatchParen", { bg = "#00ffff", reverse = true })
vim.api.nvim_set_hl(0, "ToolbarLine", { bg = "#d3d3d3", underline = true })
vim.api.nvim_set_hl(0, "ToolbarButton", { fg = "#ffffff", bg = "#666666", bold = true })
vim.api.nvim_set_hl(0, "Comment", { fg = "#0000ff", bold = true })
vim.api.nvim_set_hl(0, "Constant", { fg = "#ff00ff", underline = true })
vim.api.nvim_set_hl(0, "Special", { fg = "#6a5acd", bold = true })
vim.api.nvim_set_hl(0, "Identifier", { fg = "#008b8b", underline = true })
vim.api.nvim_set_hl(0, "Statement", { fg = "#a52a2a", bold = true })
vim.api.nvim_set_hl(0, "PreProc", { fg = "#6a0dad", underline = true })
vim.api.nvim_set_hl(0, "Type", { fg = "#2e8b57", bold = true, underline = true })
vim.api.nvim_set_hl(0, "Underlined", { fg = "#6a5acd", underline = true })
vim.api.nvim_set_hl(0, "Ignore", { fg = "bg" })
vim.api.nvim_set_hl(0, "Added", { fg = "#2e8b57" })
vim.api.nvim_set_hl(0, "Changed", { fg = "#1e90ff" })
vim.api.nvim_set_hl(0, "Removed", { fg = "#ff0000" })
vim.api.nvim_set_hl(0, "Error", { fg = "#ffffff", bg = "#ff0000", reverse = true })
vim.api.nvim_set_hl(0, "Todo", { fg = "#0000ff", bg = "#ffff00" })
vim.api.nvim_set_hl(0, "String", { link = "Constant" })
vim.api.nvim_set_hl(0, "Character", { link = "Constant" })
vim.api.nvim_set_hl(0, "Number", { link = "Constant" })
vim.api.nvim_set_hl(0, "Boolean", { link = "Constant" })
vim.api.nvim_set_hl(0, "Float", { link = "Number" })
vim.api.nvim_set_hl(0, "Function", { link = "Identifier" })
vim.api.nvim_set_hl(0, "Conditional", { link = "Statement" })
vim.api.nvim_set_hl(0, "Repeat", { link = "Statement" })
vim.api.nvim_set_hl(0, "Label", { link = "Statement" })
vim.api.nvim_set_hl(0, "Operator", { link = "Statement" })
vim.api.nvim_set_hl(0, "Keyword", { link = "Statement" })
vim.api.nvim_set_hl(0, "Exception", { link = "Statement" })
vim.api.nvim_set_hl(0, "Include", { link = "PreProc" })
vim.api.nvim_set_hl(0, "Define", { link = "PreProc" })
vim.api.nvim_set_hl(0, "Macro", { link = "PreProc" })
vim.api.nvim_set_hl(0, "PreCondit", { link = "PreProc" })
vim.api.nvim_set_hl(0, "StorageClass", { link = "Type" })
vim.api.nvim_set_hl(0, "Structure", { link = "Type" })
vim.api.nvim_set_hl(0, "Typedef", { link = "Type" })
vim.api.nvim_set_hl(0, "Tag", { link = "Special" })
vim.api.nvim_set_hl(0, "SpecialChar", { link = "Special" })
vim.api.nvim_set_hl(0, "Delimiter", { link = "Special" })
vim.api.nvim_set_hl(0, "SpecialComment", { link = "Special" })
vim.api.nvim_set_hl(0, "Debug", { link = "Special" })
vim.api.nvim_set_hl(0, "GitGutterAddInvisible", { fg = "bg", bg = "#bebebe" })
vim.api.nvim_set_hl(0, "GitGutterChangeInvisible", { fg = "bg", bg = "#bebebe" })
vim.api.nvim_set_hl(0, "GitGutterDeleteInvisible", { fg = "bg", bg = "#bebebe" })
vim.api.nvim_set_hl(0, "GitGutterChangeDeleteInvisible", { link = "GitGutterChangeInvisible" })
vim.api.nvim_set_hl(0, "GitGutterAdd", { bg = "#bebebe" })
vim.api.nvim_set_hl(0, "GitGutterChange", { bg = "#bebebe" })
vim.api.nvim_set_hl(0, "GitGutterDelete", { fg = "#0000ff", bg = "#bebebe" })
vim.api.nvim_set_hl(0, "GitGutterChangeDelete", { link = "GitGutterChange" })
vim.api.nvim_set_hl(0, "GitGutterAddLine", { link = "DiffAdd" })
vim.api.nvim_set_hl(0, "GitGutterChangeLine", { link = "DiffChange" })
vim.api.nvim_set_hl(0, "GitGutterDeleteLine", { link = "DiffDelete" })
vim.api.nvim_set_hl(0, "GitGutterChangeDeleteLine", { link = "GitGutterChangeLine" })
vim.api.nvim_set_hl(0, "GitGutterAddLineNr", { link = "CursorLineNr" })
vim.api.nvim_set_hl(0, "GitGutterChangeLineNr", { link = "CursorLineNr" })
vim.api.nvim_set_hl(0, "GitGutterDeleteLineNr", { link = "CursorLineNr" })
vim.api.nvim_set_hl(0, "GitGutterChangeDeleteLineNr", { link = "GitGutterChangeLineNr" })
vim.api.nvim_set_hl(0, "GitGutterAddIntraLine", { reverse = true })
vim.api.nvim_set_hl(0, "GitGutterDeleteIntraLine", { reverse = true })
vim.api.nvim_set_hl(0, "diffAdded", {})
vim.api.nvim_set_hl(0, "diffChanged", {})
vim.api.nvim_set_hl(0, "diffRemoved", {})
vim.api.nvim_set_hl(0, "NONE", {})
vim.api.nvim_set_hl(0, "Floaterm", { link = "Normal" })
vim.api.nvim_set_hl(0, "FloatermNC", { link = "NormalNC" })
vim.api.nvim_set_hl(0, "NormalNC", {})
vim.api.nvim_set_hl(0, "FloatermBorder", { link = "NormalFloat" })
vim.api.nvim_set_hl(0, "NormalFloat", {})
vim.api.nvim_set_hl(0, "airline_x_inactive", { fg = "#4e4e4e", bg = "#303030" })
vim.api.nvim_set_hl(0, "airline_x_inactive_bold", { fg = "#4e4e4e", bg = "#303030", bold = true })
vim.api.nvim_set_hl(0, "airline_x_inactive_red", { fg = "#ff0000", bg = "#303030" })
vim.api.nvim_set_hl(0, "airline_y_inactive", { fg = "#4e4e4e", bg = "#262626" })
vim.api.nvim_set_hl(0, "airline_y_inactive_bold", { fg = "#4e4e4e", bg = "#262626", bold = true })
vim.api.nvim_set_hl(0, "airline_y_inactive_red", { fg = "#ff0000", bg = "#262626" })
vim.api.nvim_set_hl(0, "airline_z_inactive", { fg = "#4e4e4e", bg = "#1c1c1c" })
vim.api.nvim_set_hl(0, "airline_z_inactive_bold", { fg = "#4e4e4e", bg = "#1c1c1c", bold = true })
vim.api.nvim_set_hl(0, "airline_z_inactive_red", { fg = "#ff0000", bg = "#1c1c1c" })
vim.api.nvim_set_hl(0, "airline_term_inactive", { fg = "#9cffd3", bg = "#202020" })
vim.api.nvim_set_hl(0, "airline_term_inactive_bold", { fg = "#9cffd3", bg = "#202020", bold = true })
vim.api.nvim_set_hl(0, "airline_term_inactive_red", { fg = "#ff0000", bg = "#202020" })
vim.api.nvim_set_hl(0, "airline_error_inactive", { fg = "#000000", bg = "#990000" })
vim.api.nvim_set_hl(0, "airline_error_inactive_bold", { fg = "#000000", bg = "#990000", bold = true })
vim.api.nvim_set_hl(0, "airline_error_inactive_red", { fg = "#ff0000", bg = "#990000" })
vim.api.nvim_set_hl(0, "airline_a_inactive", { fg = "#4e4e4e", bg = "#1c1c1c" })
vim.api.nvim_set_hl(0, "airline_a_inactive_bold", { fg = "#4e4e4e", bg = "#1c1c1c", bold = true })
vim.api.nvim_set_hl(0, "airline_a_inactive_red", { fg = "#ff0000", bg = "#1c1c1c" })
vim.api.nvim_set_hl(0, "airline_b_inactive", { fg = "#4e4e4e", bg = "#262626" })
vim.api.nvim_set_hl(0, "airline_b_inactive_bold", { fg = "#4e4e4e", bg = "#262626", bold = true })
vim.api.nvim_set_hl(0, "airline_b_inactive_red", { fg = "#ff0000", bg = "#262626" })
vim.api.nvim_set_hl(0, "airline_c_inactive", { fg = "#4e4e4e", bg = "#303030" })
vim.api.nvim_set_hl(0, "airline_c_inactive_bold", { fg = "#4e4e4e", bg = "#303030", bold = true })
vim.api.nvim_set_hl(0, "airline_c_inactive_red", { fg = "#ff0000", bg = "#303030" })
vim.api.nvim_set_hl(0, "airline_warning_inactive", { fg = "#000000", bg = "#df5f00" })
vim.api.nvim_set_hl(0, "airline_warning_inactive_bold", { fg = "#000000", bg = "#df5f00", bold = true })
vim.api.nvim_set_hl(0, "airline_warning_inactive_red", { fg = "#ff0000", bg = "#df5f00" })
vim.api.nvim_set_hl(0, "airline_x", { fg = "#9cffd3", bg = "#202020" })
vim.api.nvim_set_hl(0, "airline_x_bold", { fg = "#9cffd3", bg = "#202020", bold = true })
vim.api.nvim_set_hl(0, "airline_x_red", { fg = "#ff0000", bg = "#202020" })
vim.api.nvim_set_hl(0, "airline_y", { fg = "#ffffff", bg = "#444444" })
vim.api.nvim_set_hl(0, "airline_y_bold", { fg = "#ffffff", bg = "#444444", bold = true })
vim.api.nvim_set_hl(0, "airline_y_red", { fg = "#ff0000", bg = "#444444" })
vim.api.nvim_set_hl(0, "airline_z", { fg = "#00005f", bg = "#00d700" })
vim.api.nvim_set_hl(0, "airline_z_bold", { fg = "#00005f", bg = "#00d700", bold = true })
vim.api.nvim_set_hl(0, "airline_z_red", { fg = "#ff0000", bg = "#00d700" })
vim.api.nvim_set_hl(0, "airline_term", { fg = "#9cffd3", bg = "#202020" })
vim.api.nvim_set_hl(0, "airline_term_bold", { fg = "#9cffd3", bg = "#202020", bold = true })
vim.api.nvim_set_hl(0, "airline_term_red", { fg = "#ff0000", bg = "#202020" })
vim.api.nvim_set_hl(0, "airline_error", { fg = "#000000", bg = "#990000" })
vim.api.nvim_set_hl(0, "airline_error_bold", { fg = "#000000", bg = "#990000", bold = true })
vim.api.nvim_set_hl(0, "airline_error_red", { fg = "#ff0000", bg = "#990000" })
vim.api.nvim_set_hl(0, "airline_a", { fg = "#00005f", bg = "#00d700" })
vim.api.nvim_set_hl(0, "airline_a_bold", { fg = "#00005f", bg = "#00d700", bold = true })
vim.api.nvim_set_hl(0, "airline_a_red", { fg = "#ff0000", bg = "#00d700" })
vim.api.nvim_set_hl(0, "airline_b", { fg = "#ffffff", bg = "#444444" })
vim.api.nvim_set_hl(0, "airline_b_bold", { fg = "#ffffff", bg = "#444444", bold = true })
vim.api.nvim_set_hl(0, "airline_b_red", { fg = "#ff0000", bg = "#444444" })
vim.api.nvim_set_hl(0, "airline_c", { fg = "#9cffd3", bg = "#202020" })
vim.api.nvim_set_hl(0, "airline_c_bold", { fg = "#9cffd3", bg = "#202020", bold = true })
vim.api.nvim_set_hl(0, "airline_c_red", { fg = "#ff0000", bg = "#202020" })
vim.api.nvim_set_hl(0, "airline_warning", { fg = "#000000", bg = "#df5f00" })
vim.api.nvim_set_hl(0, "airline_warning_bold", { fg = "#000000", bg = "#df5f00", bold = true })
vim.api.nvim_set_hl(0, "airline_warning_red", { fg = "#ff0000", bg = "#df5f00" })
vim.api.nvim_set_hl(0, "airline_tablabel", { fg = "#ffffff", bg = "#444444" })
vim.api.nvim_set_hl(0, "airline_tab", { fg = "#4e4e4e", bg = "#303030" })
vim.api.nvim_set_hl(0, "airline_tabsel", { fg = "#00005f", bg = "#dfff00" })
vim.api.nvim_set_hl(0, "airline_tabtype", { fg = "#000000", bg = "#ffaf00" })
vim.api.nvim_set_hl(0, "airline_tabfill", { fg = "#9cffd3", bg = "#202020" })
vim.api.nvim_set_hl(0, "airline_tabmod", { fg = "#00005f", bg = "#00dfff" })
vim.api.nvim_set_hl(0, "airline_tabmod_unsel", { fg = "#ffffff", bg = "#5f005f" })
vim.api.nvim_set_hl(0, "airline_tabhid", { fg = "#9cffd3", bg = "#202020" })
vim.api.nvim_set_hl(0, "airline_tablabel_right", { fg = "#ffffff", bg = "#444444" })
vim.api.nvim_set_hl(0, "airline_tab_right", { fg = "#4e4e4e", bg = "#303030" })
vim.api.nvim_set_hl(0, "airline_tabsel_right", { fg = "#00005f", bg = "#dfff00" })
vim.api.nvim_set_hl(0, "airline_tabmod_right", { fg = "#00005f", bg = "#00dfff" })
vim.api.nvim_set_hl(0, "airline_tabhid_right", { fg = "#9cffd3", bg = "#202020" })
vim.api.nvim_set_hl(0, "airline_tabmod_unsel_right", { fg = "#ffffff", bg = "#5f005f" })
vim.api.nvim_set_hl(0, "airline_a_to_airline_b", { fg = "#00d700", bg = "#444444" })
vim.api.nvim_set_hl(0, "airline_b_to_airline_c", { fg = "#444444", bg = "#202020" })
vim.api.nvim_set_hl(0, "airline_c_to_airline_x", { fg = "#202020", bg = "#202020" })
vim.api.nvim_set_hl(0, "airline_x_to_airline_y", { fg = "#444444", bg = "#202020" })
vim.api.nvim_set_hl(0, "airline_y_to_airline_z", { fg = "#00d700", bg = "#444444" })
vim.api.nvim_set_hl(0, "airline_z_to_airline_warning", { fg = "#df5f00", bg = "#00d700" })
vim.api.nvim_set_hl(0, "airline_warning_to_airline_error", { fg = "#990000", bg = "#df5f00" })
vim.api.nvim_set_hl(0, "lspReference", {})
vim.api.nvim_set_hl(0, "LspErrorHighlight", {})
vim.api.nvim_set_hl(0, "LspWarningHighlight", {})
vim.api.nvim_set_hl(0, "LspInformationHighlight", {})
vim.api.nvim_set_hl(0, "LspHintHighlight", {})
vim.api.nvim_set_hl(0, "LspErrorText", {})
vim.api.nvim_set_hl(0, "LspWarningText", {})
vim.api.nvim_set_hl(0, "LspInformationText", {})
vim.api.nvim_set_hl(0, "LspHintText", {})
vim.api.nvim_set_hl(0, "LspErrorLine", {})
vim.api.nvim_set_hl(0, "LspWarningLine", {})
vim.api.nvim_set_hl(0, "LspInformationLine", {})
vim.api.nvim_set_hl(0, "LspHintLine", {})
vim.api.nvim_set_hl(0, "LspErrorVirtualText", {})
vim.api.nvim_set_hl(0, "LspWarningVirtualText", {})
vim.api.nvim_set_hl(0, "LspInformationVirtualText", {})
vim.api.nvim_set_hl(0, "LspHintVirtualText", {})
vim.api.nvim_set_hl(0, "LspCodeActionText", {})
vim.api.nvim_set_hl(0, "LspCodeActionLine", {})
vim.api.nvim_set_hl(0, "airline_tabfill_to_airline_tabfill", { fg = "#202020", bg = "#202020" })
vim.api.nvim_set_hl(0, "airline_tabfill_to_airline_tablabel_right", { fg = "#444444", bg = "#202020" })
vim.api.nvim_set_hl(0, "airline_tabsel_to_airline_tabfill", { fg = "#dfff00", bg = "#202020" })
vim.api.nvim_set_hl(0, "airline_c1_inactive", { fg = "#4e4e4e", bg = "#303030" })
vim.api.nvim_set_hl(0, "airline_tabfill_to_airline_tablabel_right_inactive", {})
vim.api.nvim_set_hl(0, "airline_x_to_airline_y_inactive", { fg = "#262626", bg = "#303030" })
vim.api.nvim_set_hl(0, "airline_z_to_airline_warning_inactive", { fg = "#df5f00", bg = "#1c1c1c" })
vim.api.nvim_set_hl(0, "airline_tabfill_to_airline_tabfill_inactive", {})
vim.api.nvim_set_hl(0, "airline_c_to_airline_x_inactive", { fg = "#303030", bg = "#303030" })
vim.api.nvim_set_hl(0, "airline_tabsel_to_airline_tabfill_inactive", {})
vim.api.nvim_set_hl(0, "airline_a_to_airline_b_inactive", { fg = "#1c1c1c", bg = "#262626" })
vim.api.nvim_set_hl(0, "airline_warning_to_airline_error_inactive", { fg = "#990000", bg = "#df5f00" })
vim.api.nvim_set_hl(0, "airline_y_to_airline_z_inactive", { fg = "#1c1c1c", bg = "#262626" })
vim.api.nvim_set_hl(0, "airline_b_to_airline_c_inactive", { fg = "#262626", bg = "#303030" })
vim.api.nvim_set_hl(0, "airline_tab_to_airline_tabfill", { fg = "#303030", bg = "#202020" })
vim.api.nvim_set_hl(0, "airline_c1_to_airline_x", {})
vim.api.nvim_set_hl(0, "NERDTreeIgnore", { link = "Ignore" })
vim.api.nvim_set_hl(0, "NERDTreeUp", { link = "Directory" })
vim.api.nvim_set_hl(0, "NERDTreeHelpKey", { link = "Identifier" })
vim.api.nvim_set_hl(0, "NERDTreeHelpTitle", { link = "Macro" })
vim.api.nvim_set_hl(0, "NERDTreeToggleOn", { link = "Question" })
vim.api.nvim_set_hl(0, "NERDTreeToggleOff", { link = "WarningMsg" })
vim.api.nvim_set_hl(0, "NERDTreeHelpCommand", { link = "Identifier" })
vim.api.nvim_set_hl(0, "NERDTreeHelp", { link = "String" })
vim.api.nvim_set_hl(0, "NERDTreeDir", { link = "Directory" })
vim.api.nvim_set_hl(0, "NERDTreeFile", { link = "Normal" })
vim.api.nvim_set_hl(0, "NERDTreeLinkTarget", { link = "Type" })
vim.api.nvim_set_hl(0, "NERDTreeLinkFile", { link = "Macro" })
vim.api.nvim_set_hl(0, "NERDTreeLinkDir", { link = "Macro" })
vim.api.nvim_set_hl(0, "NERDTreeNodeDelimiters", {})
vim.api.nvim_set_hl(0, "NERDTreeDirSlash", { link = "Identifier" })
vim.api.nvim_set_hl(0, "NERDTreeClosable", { link = "Directory" })
vim.api.nvim_set_hl(0, "NERDTreeOpenable", { link = "Directory" })
vim.api.nvim_set_hl(0, "NERDTreeRO", { link = "WarningMsg" })
vim.api.nvim_set_hl(0, "NERDTreeBookmarkName", { link = "Identifier" })
vim.api.nvim_set_hl(0, "NERDTreeExecFile", { link = "Title" })
vim.api.nvim_set_hl(0, "NERDTreeLink", {})
vim.api.nvim_set_hl(0, "NERDTreeFlags", { link = "Number" })
vim.api.nvim_set_hl(0, "NERDTreeCWD", { link = "Statement" })
vim.api.nvim_set_hl(0, "NERDTreeBookmarksLeader", { link = "Ignore" })
vim.api.nvim_set_hl(0, "NERDTreeBookmarksHeader", { link = "Statement" })
vim.api.nvim_set_hl(0, "NERDTreeBookmark", { link = "Normal" })
vim.api.nvim_set_hl(0, "NERDTreePart", { link = "Special" })
vim.api.nvim_set_hl(0, "NERDTreePartFile", { link = "Type" })
vim.api.nvim_set_hl(0, "NERDTreeCurrentNode", { link = "Search" })
vim.api.nvim_set_hl(0, "hideBracketsInNerdTree", {})
vim.api.nvim_set_hl(0, "airline_c3_inactive", {})
vim.api.nvim_set_hl(0, "airline_c1_inactive_bold", {})
vim.api.nvim_set_hl(0, "airline_c1_inactive_red", {})
vim.api.nvim_set_hl(0, "airline_c1_to_airline_x_inactive", {})
vim.api.nvim_set_hl(0, "airline_tab_to_airline_tabfill_inactive", {})
vim.api.nvim_set_hl(0, "airline_c1_to_airline_x_bold", {})
vim.api.nvim_set_hl(0, "airline_c1_to_airline_x_red", {})
vim.api.nvim_set_hl(0, "airline_c1_to_airline_x_inactive_inactive", {})
vim.api.nvim_set_hl(0, "airline_c1_to_airline_x_inactive_inactive_bold", {})
vim.api.nvim_set_hl(0, "airline_c1_to_airline_x_inactive_inactive_red", {})
vim.api.nvim_set_hl(0, "cStatement", { link = "Statement" })
vim.api.nvim_set_hl(0, "cLabel", { link = "Label" })
vim.api.nvim_set_hl(0, "cConditional", { link = "Conditional" })
vim.api.nvim_set_hl(0, "cRepeat", { link = "Repeat" })
vim.api.nvim_set_hl(0, "cTodo", { link = "Todo" })
vim.api.nvim_set_hl(0, "cBadContinuation", { link = "Error" })
vim.api.nvim_set_hl(0, "cSpecial", { link = "SpecialChar" })
vim.api.nvim_set_hl(0, "cFormat", { link = "cSpecial" })
vim.api.nvim_set_hl(0, "cString", { link = "String" })
vim.api.nvim_set_hl(0, "cCppString", { link = "cString" })
vim.api.nvim_set_hl(0, "cSpaceError", { link = "cError" })
vim.api.nvim_set_hl(0, "cCppSkip", {})
vim.api.nvim_set_hl(0, "cCharacter", { link = "Character" })
vim.api.nvim_set_hl(0, "cSpecialError", { link = "cError" })
vim.api.nvim_set_hl(0, "cSpecialCharacter", { link = "cSpecial" })
vim.api.nvim_set_hl(0, "cBadBlock", {})
vim.api.nvim_set_hl(0, "cCurlyError", { link = "cError" })
vim.api.nvim_set_hl(0, "cErrInParen", { link = "cError" })
vim.api.nvim_set_hl(0, "cCppParen", {})
vim.api.nvim_set_hl(0, "cErrInBracket", { link = "cError" })
vim.api.nvim_set_hl(0, "cCppBracket", {})
vim.api.nvim_set_hl(0, "cBlock", {})
vim.api.nvim_set_hl(0, "cParenError", { link = "cError" })
vim.api.nvim_set_hl(0, "cIncluded", { link = "cString" })
vim.api.nvim_set_hl(0, "cCommentSkip", { link = "cComment" })
vim.api.nvim_set_hl(0, "cCommentString", { link = "cString" })
vim.api.nvim_set_hl(0, "cComment2String", { link = "cString" })
vim.api.nvim_set_hl(0, "cCommentStartError", { link = "cError" })
vim.api.nvim_set_hl(0, "cUserLabel", { link = "Label" })
vim.api.nvim_set_hl(0, "cBitField", {})
vim.api.nvim_set_hl(0, "cOctalZero", { link = "PreProc" })
vim.api.nvim_set_hl(0, "cNumber", { link = "Number" })
vim.api.nvim_set_hl(0, "cFloat", { link = "Float" })
vim.api.nvim_set_hl(0, "cOctal", { link = "Number" })
vim.api.nvim_set_hl(0, "cOctalError", { link = "cError" })
vim.api.nvim_set_hl(0, "cNumbersCom", {})
vim.api.nvim_set_hl(0, "cParen", {})
vim.api.nvim_set_hl(0, "cBracket", {})
vim.api.nvim_set_hl(0, "cNumbers", {})
vim.api.nvim_set_hl(0, "cWrongComTail", { link = "cError" })
vim.api.nvim_set_hl(0, "cCommentL", { link = "cComment" })
vim.api.nvim_set_hl(0, "cCommentStart", { link = "cComment" })
vim.api.nvim_set_hl(0, "cComment", { link = "Comment" })
vim.api.nvim_set_hl(0, "cCommentError", { link = "cError" })
vim.api.nvim_set_hl(0, "cOperator", { link = "Operator" })
vim.api.nvim_set_hl(0, "cType", { link = "Type" })
vim.api.nvim_set_hl(0, "cTypedef", { link = "Structure" })
vim.api.nvim_set_hl(0, "cStructure", { link = "Structure" })
vim.api.nvim_set_hl(0, "cStorageClass", { link = "StorageClass" })
vim.api.nvim_set_hl(0, "cConstant", { link = "Constant" })
vim.api.nvim_set_hl(0, "cPreCondit", { link = "PreCondit" })
vim.api.nvim_set_hl(0, "cPreConditMatch", { link = "cPreCondit" })
vim.api.nvim_set_hl(0, "cCppInIf", {})
vim.api.nvim_set_hl(0, "cCppInElse", {})
vim.api.nvim_set_hl(0, "cCppInElse2", { link = "cCppOutIf2" })
vim.api.nvim_set_hl(0, "cCppOutIf", {})
vim.api.nvim_set_hl(0, "cCppOutIf2", { link = "cCppOut" })
vim.api.nvim_set_hl(0, "cCppOutElse", {})
vim.api.nvim_set_hl(0, "cCppInSkip", {})
vim.api.nvim_set_hl(0, "cCppOutSkip", { link = "cCppOutIf2" })
vim.api.nvim_set_hl(0, "cCppOutWrapper", { link = "cPreCondit" })
vim.api.nvim_set_hl(0, "cCppInWrapper", { link = "cCppOutWrapper" })
vim.api.nvim_set_hl(0, "cPreProc", { link = "PreProc" })
vim.api.nvim_set_hl(0, "cInclude", { link = "Include" })
vim.api.nvim_set_hl(0, "cDefine", { link = "Macro" })
vim.api.nvim_set_hl(0, "cMulti", {})
vim.api.nvim_set_hl(0, "cPragma", {})
vim.api.nvim_set_hl(0, "cUserCont", {})
vim.api.nvim_set_hl(0, "cError", { link = "Error" })
vim.api.nvim_set_hl(0, "cCppOut", { link = "Comment" })
vim.api.nvim_set_hl(0, "cUserFunction", { link = "Function" })
vim.api.nvim_set_hl(0, "cStructMember", {})
vim.api.nvim_set_hl(0, "cppTemplateKeyword", {})
vim.api.nvim_set_hl(0, "cAnsiName", { link = "Identifier" })
vim.api.nvim_set_hl(0, "cBoolean", { link = "Boolean" })
vim.api.nvim_set_hl(0, "cppStatement", { link = "Statement" })
vim.api.nvim_set_hl(0, "cppAccess", { link = "cppStatement" })
vim.api.nvim_set_hl(0, "cppModifier", { link = "Statement" })
vim.api.nvim_set_hl(0, "cppType", { link = "Type" })
vim.api.nvim_set_hl(0, "cppExceptions", { link = "Exception" })
vim.api.nvim_set_hl(0, "cppOperator", { link = "Operator" })
vim.api.nvim_set_hl(0, "cppCast", { link = "cppStatement" })
vim.api.nvim_set_hl(0, "cppStorageClass", { link = "StorageClass" })
vim.api.nvim_set_hl(0, "cppStructure", { link = "Structure" })
vim.api.nvim_set_hl(0, "cppBoolean", { link = "Boolean" })
vim.api.nvim_set_hl(0, "cppConstant", { link = "Constant" })
vim.api.nvim_set_hl(0, "cppRawStringDelimiter", { link = "Delimiter" })
vim.api.nvim_set_hl(0, "cppRawString", { link = "String" })
vim.api.nvim_set_hl(0, "cppNumber", { link = "Number" })
vim.api.nvim_set_hl(0, "cppFloat", { link = "Number" })
vim.api.nvim_set_hl(0, "cppNumbers", {})
vim.api.nvim_set_hl(0, "cppString", { link = "String" })
vim.api.nvim_set_hl(0, "cppCharacter", { link = "cCharacter" })
vim.api.nvim_set_hl(0, "cppSpecialError", { link = "cSpecialError" })
vim.api.nvim_set_hl(0, "cppSpecialCharacter", { link = "cSpecialCharacter" })
vim.api.nvim_set_hl(0, "cppModule", { link = "Include" })
vim.api.nvim_set_hl(0, "cppMinMax", {})
vim.api.nvim_set_hl(0, "cppSTLdefine", { link = "Constant" })
vim.api.nvim_set_hl(0, "cppSTLnamespace", { link = "Constant" })
vim.api.nvim_set_hl(0, "cppSTLconstant", { link = "Constant" })
vim.api.nvim_set_hl(0, "cppSTLvariable", { link = "Identifier" })
vim.api.nvim_set_hl(0, "cppSTLexception", { link = "Type" })
vim.api.nvim_set_hl(0, "cppSTLios", { link = "Function" })
vim.api.nvim_set_hl(0, "cppSTLtype", { link = "Type" })
vim.api.nvim_set_hl(0, "cppSTLtypedef", { link = "Typedef" })
vim.api.nvim_set_hl(0, "cppSTLiterator", { link = "Type" })
vim.api.nvim_set_hl(0, "cppSTLfunction", { link = "Function" })
vim.api.nvim_set_hl(0, "cppSTLenum", { link = "Typedef" })
vim.api.nvim_set_hl(0, "cppSTLbool", { link = "Boolean" })
vim.api.nvim_set_hl(0, "cppSTLconcept", { link = "Typedef" })
